### ISSUE TITLE
nb-cli和pip都是安装失败，找不到包

### ISSUE THREAD

**Issue by FuYon** [mnixry/nonebot-plugin-gocqhttp#1]

**Comment by FuYon** [comment]
![image](https://user-images.githubusercontent.com/57851695/151308113-fcb2e38d-74ea-4707-a62f-059bb440454d.png)

**Comment by mnixry** [comment]
好像是清华源还没同步上, 我看一眼咋回事 :rofl:

**Comment by mnixry** [comment]
确实是清华源还没同步上, 不太应该 都发布好几天了
https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/nonebot-plugin-gocqhttp

**Comment by mnixry** [comment]
华为源同步上了
https://repo.huaweicloud.com/repository/pypi/simple/nonebot-plugin-gocqhttp/

~~看来是清华源这次拉了~~

---

这个issue先关了, 有什么使用上的问题欢迎随时reopen或者开个新issue
