### ISSUE TITLE
添加多个账号后，WebUI 上某个账号会无法显示进程日志

### ISSUE THREAD

**Issue by MistEO** [mnixry/nonebot-plugin-gocqhttp#118]
显示 `日志条数 58 条`，但右边并没有输出

![image](https://user-images.githubusercontent.com/18511905/165010973-5c43bb52-eb07-4d17-9124-5b3e97559cb4.png)

由于我对 Web 实在一窍不通，不知道还能提供什么其他有用的信息（~~菜的理直气壮！~~

**Comment by MistEO** [comment]
另外当账号多了之后，WebUI 会变得非常卡，一直转圈圈。看了下 nb 那边的输出是正常的没有卡的迹象，CPU 和内存占用率也并不高。不知道和什么有关？

**Comment by MistEO** [comment]
我明白了，好像是日志的总条数有限制，这个账号的短时间内没有消息，日志就被其他账号的刷掉了

**Comment by mnixry** [comment]
> 我明白了，好像是日志的总条数有限制，这个账号的短时间内没有消息，日志就被其他账号的刷掉了

是 只会保留五分钟内的日志，可以在process_kwargs里面改

**Comment by mnixry** [comment]
> 另外当账号多了之后，WebUI 会变得非常卡，一直转圈圈。看了下 nb 那边的输出是正常的没有卡的迹象，CPU 和内存占用率也并不高。不知道和什么有关？

具体是多少账号）我没那么多测试不了）
