### ISSUE TITLE
长时间开启 WebUI 后会变得非常卡

### ISSUE THREAD

**Issue by MistEO** [mnixry/nonebot-plugin-gocqhttp#124]
昨天说的一直转圈圈的问题，应该不是多账号导致的（但是多账号可能会导致问题更容易出现？目前未知）

长时间开启 WebUI 后，会变得非常卡，点一些按钮要过很久才有响应，一直转圈圈，还很容易出现网页未响应。

关闭网页标签并重新打开仍然会很卡，**但重启浏览器进程并再次打开网页可以 100% 解决**，然后过几个小时可能又会变得非常卡。

（可能是哪里有什么资源没有释放？泄露了？我瞎猜的）

确定排除网络问题，使用的是 `Chrome 版本 99.0.4844.84（正式版本） （64 位）`

**Comment by mnixry** [comment]
我初步怀疑这个问题可能是因为NoneBot2默认使用的ASGI服务器uvicorn使用的HTTP/1.1导致的
如果从远程访问可以考虑使用Nginx或者Caddy等支持HTTP2的工具进行反向代理
