### ISSUE TITLE
WebUI日志问题

### ISSUE THREAD

**Issue by CMHopeSunshine** [mnixry/nonebot-plugin-gocqhttp#135]
请问WebUI是必显示DEBUG日志吗，我nb日志设的INFO模式，终端输出也只是INFO，但是gocq的WebUI会显示DEBUG的日志，太刷屏了
![QQ截图20220428205434](https://user-images.githubusercontent.com/63870437/165756846-7fe05881-e338-46ac-8a98-19016453cf2b.png)

**Comment by mnixry** [comment]
> 请问WebUI是必显示DEBUG日志吗，我nb日志设的INFO模式，终端输出也只是INFO，但是gocq的WebUI会显示DEBUG的日志，太刷屏了

理论上显示内容应该是和终端一样的.... 但是我也不知道是怎么回事, 我看看

**Comment by yanyongyu** [comment]
https://github.com/mnixry/nonebot-plugin-gocqhttp/blob/7ead40b67ccce5d11ff5dbe37685e7df4f731d50/nonebot_plugin_gocqhttp/__init__.py#L33-L38

参考：https://github.com/nonebot/nonebot2/blob/master/nonebot/log.py#L96-L103

需要提供一个filter，可以`from nonebot.log import default_filter`
