### ISSUE TITLE
tomlkit.exceptions.UnexpectedCharError: Unexpected character: ',' at line 16 col 69

### ISSUE THREAD

**Issue by shenvinci** [mnixry/nonebot-plugin-gocqhttp#17]
这个项目现在支持beta版本了吗？
在运行的时候遇到了`tomlkit.exceptions.UnexpectedCharError: Unexpected character: ',' at line 16 col 69`的问题

**Comment by mnixry** [comment]
本插件是基于beta1开发的
这个问题应该是你`pyproject.toml`语法有问题, 和本插件没有关系

**Comment by shenvinci** [comment]
好的，我在试试看，谢谢呀
