### ISSUE TITLE
疑似运行过程中 accounts/binary/accounts.pkl 文件损坏

### ISSUE THREAD

**Issue by MistEO** [mnixry/nonebot-plugin-gocqhttp#186]
很正常的在服务器上挂着，突然 bot 不回消息了，于是我用手机连上去发现日志输出了一堆这个

![Screenshot_2022-06-04-00-31-21-683_com sonelli ju](https://user-images.githubusercontent.com/18511905/171907369-f449713d-8376-4da7-9d22-a2b5c73ef6b5.jpg)

然后我没多想就重启进程了，但是此时 nonebot 进程启动失败，输出这个

![image](https://user-images.githubusercontent.com/18511905/171907473-a7761858-0250-48c7-a84e-5c8af82dbdf7.png)

此时的文件是 0 

![image](https://user-images.githubusercontent.com/18511905/171907506-3b0f61d9-f5e2-46c3-85ab-00a6a04238b7.png)

**Comment by mnixry** [comment]
理论上不会发生诶

检查一下有没有可能是：

- 磁盘满了
- 服务终止没有使用SIGINT信号
- 服务终止超时时间过短，还未来得及完全停止就被SIGKILL

**Comment by MistEO** [comment]
看起来不太好查原因那总之先 close（

**Comment by MistEO** [comment]
超，刚关了 issue 顺手重启服务器了一下，又出现了。。又损坏了一次，不过还好这次我备份了。。

话说这个这个文件是实时在读写的么？为什么会出现损坏的情况呢，考不考虑出个备份恢复机制什么的_(:з」∠)_

**Comment by mnixry** [comment]
> 话说这个这个文件是实时在读写的么？为什么会出现损坏的情况呢

目前，在以下情况中，`accounts.pkl`文件会被修改：
	- 添加或者删除了一个账户
	- 关闭进程时

猜测你的问题是，服务器关机，向进程发送了SIGINT信号，程序正常关闭开始保存`accounts.pkl`
然而在保存过程中，由于进程终止时间过长，导致进程被强行终止（或者这个时候服务器已经关闭了）

你用的是Systemd管理进程吗？

**Comment by MistEO** [comment]
> > 话说这个这个文件是实时在读写的么？为什么会出现损坏的情况呢
> 
> 目前，在以下情况中，`accounts.pkl`文件会被修改：
> 
> * 添加或者删除了一个账户
> * 关闭进程时
> 
> 猜测你的问题是，服务器关机，向进程发送了SIGINT信号，程序正常关闭开始保存`accounts.pkl` 然而在保存过程中，由于进程终止时间过长，导致进程被强行终止（或者这个时候服务器已经关闭了）
> 
> 你用的是Systemd管理进程吗？

确实是 systemd

**Comment by mnixry** [comment]
这样吧, 我把在开启和停止过程中的文件保存逻辑删了, 只在添加和删除账户的时候进行保存

这样应该会稳一些
