### ISSUE TITLE
每当我试图访问webui时gocq就会弹警告，webui页面Bad Request

### ISSUE THREAD

**Issue by QinCaii** [mnixry/nonebot-plugin-gocqhttp#187]
警告内容：处理websocket请求时出现错误：websocket:the client is not using the websocket protocol:'upgrade'token not found in 'Connection' header
我不理解这是什么意思
我是用公网ip:监听端口/go-cqhttp/访问的
连接服务列表使用的是正向ws和http通信

**Comment by mnixry** [comment]
你应该访问的是nonebot的监听端口，而不是gocq的

**Comment by QinCaii** [comment]
emmm, 访问nonebot的端口是拒绝连接呢
