### ISSUE TITLE
`restart_interval` 参数使用不合理

### ISSUE THREAD

**Issue by MistEO** [mnixry/nonebot-plugin-gocqhttp#240]
https://github.com/mnixry/nonebot-plugin-gocqhttp/blob/a73967347c1b41cc3795ebc8700a93b88a59816f/nonebot_plugin_gocqhttp/process/process.py#L160

https://github.com/mnixry/nonebot-plugin-gocqhttp/blob/a73967347c1b41cc3795ebc8700a93b88a59816f/nonebot_plugin_gocqhttp/process/process.py#L168

这俩不应该使用同一个参数，我这里账号比较多，想把 `restart_interval` 设置大一点，但却造成了整个进程启动的时候，几个账号登陆完，再过很久（跑完了 168 行那个）才会去登剩下的账号

**Comment by mnixry** [comment]
其实这个问题我觉得应该是这个`sleep`同步操作把线程池填满了导致之后的操作都在等待

如果你想要一起启动应该也可以直接考虑把start这个函数改成异步
