### ISSUE TITLE
账号在被冻结 - 手动解冻 - 重新登录时，提示密码错误，发现密码多了一个空格

### ISSUE THREAD

**Issue by MistEO** [mnixry/nonebot-plugin-gocqhttp#249]
一开始以为是个例，密码搞错了，然后现在出现两三次了

具体现象为：
1. 原先正常登陆，某一天账号被冻结，手动解冻
2. 在 webui 上重新登录，提示密码错误
3. 打开 `accounts/<账号>/config.yml` 文件，发现 `account` - `password` 字段的字符串值最后多了一个空格

例如：（假设我的密码是 `1234567`，结果变成了 `1234567[空格]` 了）

![image](https://user-images.githubusercontent.com/18511905/180228569-3699c8b9-ca52-4c29-83b5-3414c614ccb1.png)

复现路径不一定准确，只是碰巧冻结重新登录发现的，可能和重新登录压根没关系，也不知道跟什么有关系，也不知道啥时候这个空格多出来的 orz

**Comment by MistEO** [comment]
补充详细一点上面的步骤 2，刚才出现的那次我的具体操作是

1. 打开 web 页面该账号的页面 `go-cqhttp/#/accounts/<账号>`
2. 点击 `启动`，没反应，于是点了 `停止`
3. 再次点击 `启动`
4. go-cqhttp 进程正常启动，web 上的开始输出进程信息
5. 选择 `传入文字到进程`，输入了 `1` （通过滑条登陆）
6. 复制滑条网址，另外打开一个网页滑动滑条
7. 回到 web 页面，go-cqhttp 输出提示密码错误

**Comment by mnixry** [comment]
有点麻烦... 看你这个操作流程感觉不像是有触发过修改密码的

**Comment by MistEO** [comment]
对了，这次的空格在前面x，即`[空格]1234567`

期间是前两天才新增的，当时正常登陆，期间也没被冻结，今天重启了一下进程发现登不上了，前面多出来个空格。咕怀疑是新增账号的时候写入就写错了
