### ISSUE TITLE
安装时报错ValueError("'tool' in toml file is not a Table!")

### ISSUE THREAD

**Issue by drway** [mnixry/nonebot-plugin-gocqhttp#289]
aliyun的Ubuntu20.04
![image](https://user-images.githubusercontent.com/78285587/185607523-a080375c-4d71-495f-9d9d-dc704cd47f36.png)
![image](https://user-images.githubusercontent.com/78285587/185607554-12a11de2-9e3d-4cc9-8170-111e83f59e32.png)

**Comment by mnixry** [comment]
感觉像是 https://github.com/nonebot/nb-cli 的问题, 如果你的问题能够稳定复现可以考虑去这里提issue
