### ISSUE TITLE
http://localhost:port/go-cqhttp/  css引入失败

### ISSUE THREAD

**Issue by damicnagisa** [mnixry/nonebot-plugin-gocqhttp#307]
python版本：3.9.13
nonebot版本：2.0.0b5

```
08-30 15:32:05 [SUCCESS] nonebot | NoneBot is initializing...
08-30 15:32:05 [INFO] nonebot | Current Env: dev
08-30 15:32:05 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 12208, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
08-30 15:32:05 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
08-30 15:32:05 [SUCCESS] nonebot | Succeeded to import "echo"
08-30 15:32:07 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
08-30 15:32:07 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
08-30 15:32:07 [SUCCESS] nonebot | Running NoneBot...
08-30 15:32:07 [DEBUG] nonebot | Loaded adapters: OneBot V11
08-30 15:32:07 [INFO] uvicorn | Will watch for changes in these directories: ['D:\\cl\\robot\\nb-robot\\nb-robot-test']
08-30 15:32:07 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:12208 (Press CTRL+C to quit)
08-30 15:32:07 [INFO] uvicorn | Started reloader process [15048] using WatchFiles
08-30 15:32:07 [SUCCESS] nonebot | NoneBot is initializing...
08-30 15:32:07 [INFO] nonebot | Current Env: dev
08-30 15:32:07 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 12208, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
08-30 15:32:07 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
08-30 15:32:07 [SUCCESS] nonebot | Succeeded to import "echo"
08-30 15:32:09 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
08-30 15:32:09 [INFO] uvicorn | Started server process [12364]
08-30 15:32:09 [INFO] uvicorn | Waiting for application startup.
08-30 15:32:09 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://127.0.0.1:12208/go-cqhttp/
08-30 15:32:09 [INFO] uvicorn | Application startup complete.
```
项目无报错
但
![image](https://user-images.githubusercontent.com/74049139/187378535-1f8d6e86-13fd-4abc-b15e-c55c69f7786c.png)
css引入失败
我试着清理了chrome的缓存和改用火狐浏览器但都没能解决问题

**Comment by mnixry** [comment]
没遇到过这个问题…你打开开发者工具看一下哪些加载失败了，错误原因是什么
按理来说这个不应该发生的

**Comment by damicnagisa** [comment]
> 没遇到过这个问题…你打开开发者工具看一下哪些加载失败了，错误原因是什么 按理来说这个不应该发生的

![image](https://user-images.githubusercontent.com/74049139/187383131-f956be4b-cc29-4547-a938-335e6065b137.png)
![image](https://user-images.githubusercontent.com/74049139/187383360-becca567-4bbf-46cd-83d7-ea82e507096a.png)
除了css好像都加载成功了

**Comment by damicnagisa** [comment]
> 没遇到过这个问题…你打开开发者工具看一下哪些加载失败了，错误原因是什么 按理来说这个不应该发生的

![image](https://user-images.githubusercontent.com/74049139/187407227-53878fae-def3-4731-9b8b-be5b4ffb3f83.png)

**Comment by mnixry** [comment]
你用本地的Python环境执行一下这个
```python
from mimetypes import guess_type

print(guess_type('xxx.css'))
```

**Comment by damicnagisa** [comment]
> 你用本地的Python环境执行一下这个
> 
> ```python
> from mimetypes import guess_type
> 
> print(guess_type('xxx.css'))
> ```

`('application/x-css', None)
08-31 09:11:57 [SUCCESS] nonebot | NoneBot is initializing...
08-31 09:11:57 [INFO] nonebot | Current Env: dev
08-31 09:11:57 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 13020, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'environment': 'dev'}
08-31 09:11:57 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
08-31 09:11:58 [SUCCESS] nonebot | Succeeded to import "echo"
08-31 09:11:59 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
08-31 09:11:59 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
08-31 09:11:59 [SUCCESS] nonebot | Running NoneBot...
08-31 09:11:59 [DEBUG] nonebot | Loaded adapters: OneBot V11
08-31 09:11:59 [INFO] uvicorn | Will watch for changes in these directories: ['D:\\cl\\robot\\nb-robot\\nb-test-5']
08-31 09:11:59 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:13020 (Press CTRL+C to quit)
08-31 09:11:59 [INFO] uvicorn | Started reloader process [6128] using WatchFiles
('application/x-css', None)
08-31 09:12:00 [SUCCESS] nonebot | NoneBot is initializing...
08-31 09:12:00 [INFO] nonebot | Current Env: dev
08-31 09:12:00 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 13020, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
08-31 09:12:00 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
08-31 09:12:00 [SUCCESS] nonebot | Succeeded to import "echo"
08-31 09:12:02 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
08-31 09:12:02 [INFO] uvicorn | Started server process [13724]
08-31 09:12:02 [INFO] uvicorn | Waiting for application startup.
08-31 09:12:02 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://127.0.0.1:13020/go-cqhttp/
08-31 09:12:02 [INFO] uvicorn | Application startup complete.`

**Comment by damicnagisa** [comment]
> 你用本地的Python环境执行一下这个
> 
> ```python
> from mimetypes import guess_type
> 
> print(guess_type('xxx.css'))
> ```

谢啦,已解决,是我注册表的问题
![image](https://user-images.githubusercontent.com/74049139/187615921-8ef7a123-24ed-4d8c-8010-900abdbafef0.png)
