### ISSUE TITLE
希望增加网页内对cqlog提供过滤器选项

### ISSUE THREAD

**Issue by BalconyJH** [mnixry/nonebot-plugin-gocqhttp#332]
效果预览（仅效果
![image](https://user-images.githubusercontent.com/73932916/190983597-4379c149-0256-4ae3-87e2-dee2ebab2c85.png)

**Comment by mnixry** [comment]
酷哦，这是什么的界面

**Comment by BalconyJH** [comment]
> 酷哦，这是什么的界面

https://github.com/joni1802/ts3-manager

**Comment by BalconyJH** [comment]
> > 酷哦，这是什么的界面
> 
> https://github.com/joni1802/ts3-manager

使用了极其先进的vue2(
