### ISSUE TITLE
在ws中怎么配置AccessToken

### ISSUE THREAD

**Issue by 18ghwg** [mnixry/nonebot-plugin-gocqhttp#339]
如标题

**Comment by mnixry** [comment]
没明白你的意思……？

**Comment by 18ghwg** [comment]
就是说，在生产环境中，怎么限制cqhttp的api调用，防止别人使用接口，我记得官方的配置文件里面有AccessToken通信秘钥，可我直接修改配置文件，在重启nonebot的时候，配置文件被本插件重置了，所以来问一下，不知道我的表述是否清楚

**Comment by mnixry** [comment]
首先，这个插件的go-cqhttp使用的是反向ws通信方式，在这种情况下gocq是客户端而不是服务端，不存在你所说的API调用问题。除非你将NoneBot的监听开放到公网，就像 #42 那样，才会使得本插件的WebUI暴露在公网而使得API能够被调用。
对于这种情况，[我在README里面已经进行了安全性告知](https://github.com/mnixry/nonebot-plugin-gocqhttp#%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8)

P.S. 如果你想修改配置文件请使用WebUI进行修改，直接修改`config.yml`会在每次启动时被覆盖。

**Comment by 18ghwg** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月30日(周五) 上午10:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mnixry/nonebot-plugin-gocqhttp] 在ws中怎么配置AccessToken (Issue #339)




 
首先，这个插件的go-cqhttp使用的是反向ws通信方式，在这种情况下gocq是客户端而不是服务端，不存在你所说的API调用问题。除非你将NoneBot的监听开放到公网，就像 #42 那样，才会使得本插件的WebUI暴露在公网而使得API能够被调用。
 对于这种情况，我在README里面已经进行了安全性告知
 
P.S. 如果你想修改配置文件请使用WebUI进行修改，直接修改config.yml会在每次启动时被覆盖。
