### ISSUE TITLE
后台连接网页端一段时间后重复报错

### ISSUE THREAD

**Issue by WindraiteLesd** [mnixry/nonebot-plugin-gocqhttp#341]
open image cache failed: 文件被其他进程占用
Process for {QQ号} exited with code 1, retrying to restart...

对后台没啥影响，bot正常运行，但导致网页端无法连接后台

**Comment by mnixry** [comment]
操作系统，插件版本都是什么👀如果可能请提供完整日志
Related: #45 #258

**Comment by WindraiteLesd** [comment]
> 操作系统，插件版本都是什么👀如果可能请提供完整日志 Possible Related: #45 #258

操作系统Windows Server 2019 Datacenter
Nonebot 2 beta5，插件版本0.6.1

有没有可能是跟这个kawaiibot插件有冲突
![image](https://user-images.githubusercontent.com/104503043/193460052-cbcda8a6-a07f-4d03-9dfa-eda6b7eec123.png)

**Comment by mnixry** [comment]
> 操作系统Windows Server 2019 Datacenter Nonebot 2 beta5，插件版本0.6.1

Windows啊……那事情确实比较多
这个错误是你什么都不做就发生了，还是进行了什么操作以后能够复现？

还有我记得这种报错应该不会影响WebUI连接的，如果可能可以描述一下“后台无法连接”具体是什么症状吗

**Comment by WindraiteLesd** [comment]
> > 操作系统Windows Server 2019 Datacenter Nonebot 2 beta5，插件版本0.6.1
> 
> Windows啊……那事情确实比较多 这个错误是你什么都不做就发生了，还是进行了什么操作以后能够复现？
> 
> 还有我记得这种报错应该不会影响WebUI连接的，如果可能可以描述一下“后台无法连接”具体是什么症状吗
说不好是为什么，因为每次刚打开是正常的，等一段时间就这样了，但感觉跟使用了什么指令没关系
后台无法连接就是一直报错
![image](https://user-images.githubusercontent.com/104503043/193460477-4ebcb2ac-d4bb-4d79-bba4-d0d8a512b720.png)

**Comment by mnixry** [comment]
> 说不好是为什么，因为每次刚打开是正常的，等一段时间就这样了 但感觉跟使用了什么指令没关系

那还是蛮奇怪的……我过会把重复进程检测加到每次进程启动之前试试

> 后台无法连接就是一直报错

这是正常的啊😥~~我还以为是直接白屏或者这一页缺元素之类的~~

**Comment by WindraiteLesd** [comment]
[ERROR] nonebot_plugin_gocqhttp | Thread <Thread(daemon-thread-(此处为qq号), started daemon 3580)> raised unknown exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
> File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot_plugin_gocqhttp\process\process.py", line 151, in _process_worker
    code = self._process_executor()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot_plugin_gocqhttp\process\process.py", line 121, in _process_executor
    for output in iter(self.process.stdout.readline, ""):
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 69: invalid continuation byte
这几天终于发现了这个问题最开始的报错信息了

**Comment by dgcccccc** [comment]
同样出现 貌似Ubuntu20.04 版本0.6.1

**Comment by mnixry** [comment]
> 同样出现 貌似Ubuntu20.04 版本0.6.1

@dgcccccc 你出现的是哪个问题, 是`DecodeError`还是WebUI反复报错?

**Comment by jieBieber** [comment]
兄弟，这个问题最后你成功解决了嘛？？？？

**Comment by mnixry** [comment]
> 兄弟，这个问题最后你成功解决了嘛？？？？

请提供你的操作系统和插件版本 以及你的问题的描述

**Comment by jieBieber** [comment]
https://github.com/mnixry/nonebot-plugin-gocqhttp/issues/341#issuecomment-1320176788

![A566C4E7B8F83491C2EA097F0CD84D3D](https://user-images.githubusercontent.com/100121431/202827985-14bcc4b3-3773-439d-90bb-5d58186d2dc0.png)

兄弟，我这边操作系统是windows 2016，插件版本是0.6.1的，问题如图一直显示 open image cache failed:文件被其他进程占用

**Comment by jieBieber** [comment]
> > 兄弟，这个问题最后你成功解决了嘛？？？？
> 
> 请提供你的操作系统和插件版本 以及你的问题的描述

![A566C4E7B8F83491C2EA097F0CD84D3D](https://user-images.githubusercontent.com/100121431/202827985-14bcc4b3-3773-439d-90bb-5d58186d2dc0.png)

兄弟，我这边操作系统是windows 2016，插件版本是0.6.1的，问题如图一直显示 open image cache failed:文件被其他进程占用

**Comment by jieBieber** [comment]
> > 兄弟，这个问题最后你成功解决了嘛？？？？
> 
> 请提供你的操作系统和插件版本 以及你的问题的描述

![image](https://user-images.githubusercontent.com/100121431/202828741-5f10c523-a7da-4dfd-b0f6-9953338a0e3b.png)


兄弟，我这边操作系统是windows 2016，插件版本是0.6.1的，问题是一直显示 open image cache failed:文件被其他进程占用

**Comment by mnixry** [comment]
尝试的修复已发布在 https://github.com/mnixry/nonebot-plugin-gocqhttp/tree/v0.6.3 

改进了对正在运行进程的检测机制, 提升了进程编码处理的鲁棒性

**Comment by jieBieber** [comment]
> 尝试的修复已发布在 https://github.com/mnixry/nonebot-plugin-gocqhttp/tree/v0.6.3
> 
> 改进了对正在运行进程的检测机制, 提升了进程编码处理的鲁棒性

嗯 好的 谢谢
