### ISSUE TITLE
网页端一直显示断开，但实际并没有

### ISSUE THREAD

**Issue by forchannot** [mnixry/nonebot-plugin-gocqhttp#362]
![image](https://user-images.githubusercontent.com/100580891/195966631-9d4131a2-e559-4e52-9b95-dccaa7918335.png)

**Comment by mnixry** [comment]
是显示了"断开"但是日志一直还是在实时更新吗?

**Comment by forchannot** [comment]
是的，用的是nginx代理，不清楚是不是因为这个的原因，在电脑本地打开显示的是连接

**Comment by mnixry** [comment]
问题信息不足，在本地开发环境无法复现~~，先把这个Issue关了~~

如果您能提供任何新的信息或者具体的复现条件，欢迎随时Reopen。如果有任何其他人遇到相关问题，可以在这里回复
