### ISSUE TITLE
插件运行后加载其他插件失败

### ISSUE THREAD

**Issue by legiorange** [mnixry/nonebot-plugin-gocqhttp#376]
```python
nonebot.load_plugins("plugins")
nonebot.load_plugin("nonebot_plugin_gocqhttp")
```

此时nonebot_plugin_gocqhttp加载，但load_plugins未加载本地插件
```
--plugins
      |--msg
            |--__init__.py
```
            
`msg/__init__.py`其具体内容：
```python
from nonebot import on_message
from nonebot.adapters.onebot.v11 import  Event

# 注册一个消息响应器
matcher = on_message()
# 注册一个消息处理器
# 并重复收到的消息
@matcher.handle()
async def handler(event: Event) -> None:
    await matcher.send(event.get_message())
```
---------------------------------------------------------

迷。

**Comment by mnixry** [comment]
请提供相关日志以便复现

**Comment by legiorange** [comment]
10-29 04:25:08 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
10-29 04:25:08 [INFO] __main__ | loadding
10-29 04:25:08 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
10-29 04:25:08 [SUCCESS] nonebot | Running NoneBot...
10-29 04:25:08 [INFO] uvicorn | Started server process [40968]
10-29 04:25:08 [INFO] uvicorn | Waiting for application startup.
10-29 04:25:09 [INFO] nonebot_plugin_gocqhttp | [3079837232] 当前版本:v1.0.0-rc3
10-29 04:25:09 [INFO] nonebot_plugin_gocqhttp | [3079837232] 将使用 device.json 内的设备信息运行Bot.
10-29 04:25:09 [INFO] nonebot_plugin_gocqhttp | [3079837232] 开始尝试登录并同步消息...
10-29 04:25:09 [INFO] nonebot_plugin_gocqhttp | [3079837232] 使用协议: Android Phone

------------------------------------------------------------------------------------------------------
因为nonebot.load_plugins("plugins")
理论上会导入  "msg"实际上没有导入，文件夹创建正确，也观察了其他机器人的写法
toml配置也没问题
，使用“nonebot_plugin_gocqhttp”时第三方插件不受影响，本地受影响。

**Comment by legiorange** [comment]
是我自己的锅， Close 了
