### ISSUE TITLE
使用ghproxy.com作为镜像代理

### ISSUE THREAD

**Issue by forchannot** [mnixry/nonebot-plugin-gocqhttp#385]
在使用插件时,fast的镜像代理总是会连接不上导致nonebot启动报错，推荐使用ghproxy.com的镜像代理，下载链接如https://ghproxy.com/https://github.com/Mrs4s/go-cqhttp/releases/download/v1.0.0-rc3/go-cqhttp_windows_amd64.zip

**Comment by mnixry** [comment]
这个有点不好做，和现在的代码设计有些不符

**Comment by forchannot** [comment]
群友已经有无数个因为这个下载失败报错来问的了😂，可以加一个自定义url功能，让我们自己添加下载链接或者多加几次超时重传来避免报错

**Comment by mnixry** [comment]
> 群友已经有无数个因为这个下载失败报错来问的了😂，可以加一个自定义url功能，让我们自己添加下载链接

看README, 其实是有的……

> 或者多加几次超时重传来避免报错

在写，我正在考虑要不要把fastgit从域名列表里面删掉

**Comment by mnixry** [comment]
改进方案已发布在 https://github.com/mnixry/nonebot-plugin-gocqhttp/tree/v0.6.3:
	- 使用了FastGit最新的镜像域名`download.fgit.ml`
	- 将下载逻辑调整为按照延迟排序, 失败以后尝试下一个
	- 将第一个尝试下载的站点改为使用Cloudflare Worker的反代`ghdown.obfs.dev`
