### ISSUE TITLE
插件安装时显示Exception: py-cpuinfo currently only works on X86 and some ARM/PPC/S390X/MIPS CPUs.

### ISSUE THREAD

**Issue by Sichongzou** [mnixry/nonebot-plugin-gocqhttp#397]
![image](https://user-images.githubusercontent.com/68594934/202597596-06f6ee97-7ef0-4776-890c-54b72cecec3b.png)
用的是腾讯云的服务器
![image](https://user-images.githubusercontent.com/68594934/202597684-963c8e7a-554f-4a91-8b73-3696d75d880e.png)
这是否意味着这块CPU不受支持，导致我无法使用这个插件

**Comment by mnixry** [comment]
感觉是这个库的问题.. 我过会看一下它的源码
应该可以手动指定下载链接的

**Comment by mnixry** [comment]
你试试用Python运行一下

```python
import platform
print(platform.machine())
```

**Comment by mnixry** [comment]
> 这是我获取到的信息 ![image](https://user-images.githubusercontent.com/68594934/202604190-1139a237-c492-4b39-b0a8-78078d677e2a.png)

能复制出来吗 这个字体看着有点奇怪

**Comment by Sichongzou** [comment]
> > 这是我收到的信息![图片](https://user-images.githubusercontent.com/68594934/202604190-1139a237-c492-4b39-b0a8-78078d677e2a.png)
> 
> 能复制出来吗这个字体看着有点奇怪
AMD64

**Comment by mnixry** [comment]
![image](https://user-images.githubusercontent.com/32300164/202605608-397d0426-89db-4a37-8122-f8b6449a7f5a.png)

那不应该匹配不上啊🤔

**Comment by Sichongzou** [comment]
这有可能是大小写的问题么

**Comment by mnixry** [comment]
> 这有可能是大小写的问题么

不是, 它已经全转小写了

总之要不你先试试重装系统? Windows架构是AMD64的应该挺多的, 出现问题应该不会现在才发现

**Comment by Sichongzou** [comment]
这台服务器上跑的服务器还挺多的，条件不允许我重装系统，但是我可以尝试重启它

**Comment by Sichongzou** [comment]
这台服务器上跑的服务还挺多的，条件不允许我重装它，但是也需我可以试试重启。

**Comment by Sichongzou** [comment]
> 再次确认一下 刚刚这个AMD64字样是否是你直接从服务器终端复制出来的?
> 
> 总感觉这个字体渲染不太正常
> 
> 然后试着查看一下 `PROCESSOR_ARCHITECTURE` 环境变量, 看看它的值是多少
我很确定这是AMD64 它也是我直接从服务器上复制下来的
我可以使用另一种终端来运行它
![image](https://user-images.githubusercontent.com/68594934/202607140-737fd177-e8e2-4a94-816a-9a6938edefc1.png)

**Comment by Sichongzou** [comment]
> 再次确认一下 刚刚这个AMD64字样是否是你直接从服务器终端复制出来的?
> 
> 总感觉这个字体渲染不太正常
> 
> 然后试着查看一下 `PROCESSOR_ARCHITECTURE` 环境变量, 看看它的值是多少

我很确定这是AMD64 它也是我直接从服务器上复制下来的
我可以使用另一种终端来运行它
![image](https://user-images.githubusercontent.com/68594934/202607256-93220b98-2205-4d6c-8452-8970138bbc9a.png)

**Comment by Sichongzou** [comment]
这是我查询的环境变量
![image](https://user-images.githubusercontent.com/68594934/202607567-8791ac46-42e7-443d-b855-e4bd1dbe1463.png)

**Comment by Sichongzou** [comment]
oh 我好像找到原因了。我使用了Clash中命令框，来帮助我通过代理的方式拉取gocq

**Comment by Sichongzou** [comment]
很抱歉由于我自身的一些原因，给您添麻烦了

**Comment by mnixry** [comment]
> oh 我好像找到原因了。我使用了Clash中命令框，来帮助我通过代理的方式拉取gocq

~~虽然但是我没想明白clash为什么会影响这个~~ 应该还是上游库的问题 我再看看

**Comment by Sichongzou** [comment]
很奇怪 我的具体操作步骤为
![image](https://user-images.githubusercontent.com/68594934/202654004-cff3c111-5bef-478a-a994-9f0efe8c97ef.png)
![image](https://user-images.githubusercontent.com/68594934/202654121-54a04bc4-54e6-49db-ace3-e1019ddc69e1.png)
![image](https://user-images.githubusercontent.com/68594934/202654032-7fd2c407-3da4-40de-a90d-e067a4ab6b46.png)
![image](https://user-images.githubusercontent.com/68594934/202654071-400af562-bf32-48f8-aebf-30120040b2c0.png)
之后我在他出来的命令框中运行我的代码 就出现了CPU不支持的情况

**Comment by Nobooooody** [comment]
> 很奇怪 我的具体操作步骤为 ![image](https://user-images.githubusercontent.com/68594934/202654004-cff3c111-5bef-478a-a994-9f0efe8c97ef.png) ![image](https://user-images.githubusercontent.com/68594934/202654121-54a04bc4-54e6-49db-ace3-e1019ddc69e1.png) ![image](https://user-images.githubusercontent.com/68594934/202654032-7fd2c407-3da4-40de-a90d-e067a4ab6b46.png) ![image](https://user-images.githubusercontent.com/68594934/202654071-400af562-bf32-48f8-aebf-30120040b2c0.png) 之后我在他出来的命令框中运行我的代码 就出现了CPU不支持的情况

以前好像也遇到过因为这个clash的terminal引起的问题
