### ISSUE TITLE
[bug]已被删除的后台进程导致程序无法正常启动

### ISSUE THREAD

**Issue by Well2333** [mnixry/nonebot-plugin-gocqhttp#401]
[问题位置](https://github.com/mnixry/nonebot-plugin-gocqhttp/blob/main/nonebot_plugin_gocqhttp/process/process.py#L165-L181)

此处对系统中所有进程全遍历一遍，与当前进程进行比较，若出现可执行文件一致或工作路径相同的情况时，便结束当前进程。

但如果出现同根目录一同被删除但进程仍挂载在后台的情况时，[此行](https://github.com/mnixry/nonebot-plugin-gocqhttp/blob/main/nonebot_plugin_gocqhttp/process/process.py#L177)便会出现 `FileNotFoundError: [Errno 2] No such file or directory: xxxxx` 的错误。

因此，个人建议应加入异常捕获或对所获取的数据进行校验，以确保不会因为意外情况导致校验失败。

完整的错误日志因包含个人信息与密码，因此不在此处放出，已通过开发者群进行提供。

**Comment by mnixry** [comment]
我这两天出个patch版本修一下吧……本来以为这个是边际条件，结果发现好像挺常见的
