### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by Cvandia** [mnixry/nonebot-plugin-gocqhttp#413]
![image](https://user-images.githubusercontent.com/106718176/206075380-3eddf658-c527-4647-bd2f-79f389dc8495.png)
![image](https://user-images.githubusercontent.com/106718176/206075421-6faa5b3a-5861-4a77-af3e-710e09854bd5.png)

**Comment by mnixry** [comment]
看起来像是程序终止的时候尝试重启了子进程，理论上不影响使用

**Comment by Cvandia** [comment]
是在启动的时候报错
![image](https://user-images.githubusercontent.com/106718176/206076139-611cc902-18ed-4d35-87f1-5f65de981c12.png)

**Comment by mnixry** [comment]
那这个就不是关键的报错，上面应该还有

**Comment by Cvandia** [comment]
![image](https://user-images.githubusercontent.com/106718176/206076478-90280f3d-7afe-4341-9e54-0b94d373260f.png)
这段吗？

**Comment by Cvandia** [comment]
问题已解决
