### ISSUE TITLE
gocq命令无法触发 /gocq也无效

### ISSUE THREAD

**Issue by BronzedOreo** [mnixry/nonebot-plugin-gocqhttp#427]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/71474660/208829604-efb65cf2-5361-4eff-ba24-fd65716190e6.png">

**Comment by mnixry** [comment]
那`/gocq`指令的日志是什么

**Comment by BronzedOreo** [comment]
没有任何回复，日志如上图

**Comment by mnixry** [comment]
> 没有任何回复，日志如上图

你这个是向Bot发送`gocq`的日志，我希望确认一下发送`/gocq`和发送`gocq`时的日志是否一致。

同时，请提供你的Bot的相关配置，包括`.env`，`.env.prod`之类的

**Comment by BronzedOreo** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/71474660/208964795-0d40c6d8-4175-4430-aab3-41fe4735ef61.png">
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/71474660/208965475-8109fe70-04fb-4959-889e-45d0077eb097.png">

**Comment by mnixry** [comment]
看了一下程式碼，確實是Bug，下個版本修復
