### ISSUE TITLE
docker部署如何设置监听地址？

### ISSUE THREAD

**Issue by LeonX86** [mnixry/nonebot-plugin-gocqhttp#428]
docker部署，网络是直接host模式（为了从公网ipv6访问）
然后测试下来在.env文件中的监听地址为127.0.0.1时候ipv4和ipv6都打不开
换成0.0.0.0，ipv4显示{"detail":"Not Found"} ipv6继续打不开
![image](https://user-images.githubusercontent.com/49100008/209344853-cff62ac0-6e91-4f3f-84a9-8d7bd6af6b59.png)
有什么好的办法吗

**Comment by mnixry** [comment]
可以看uvicorn的文档: https://www.uvicorn.org/settings/#socket-binding

> Use --host 0.0.0.0 to make the application available on your local network. IPv6 addresses are supported, for example: --host '::'.

**Comment by LeonX86** [comment]
> 可以看uvicorn的文档: https://www.uvicorn.org/settings/#socket-binding
> 
> > Use `--host 0.0.0.0` to make the application available on your local network. IPv6 addresses are supported, for example: `--host '::'`.

看了一下他的文档并搜索了一下，ipv4现在成功了，但是因为gocqhttp里默认的本地反代就是127.0.0.1
所以写ipv6 HOST=::这样子会直接连不上
![image](https://user-images.githubusercontent.com/49100008/209749688-caf88a81-ff7e-4ff6-bd31-61b2768feef2.png)
然后我看HOST这个参数好像也没法同时写两个值？
就是说只能ipv4和ipv6二选一嘛

**Comment by mnixry** [comment]
那你可以不用host网络模式（

可以用Docker带的那个端口映射开到公网，比较方便👀

**Comment by LeonX86** [comment]
docker的端口映射是只能ipv4的，ipv6的话只支持host（这似乎是docker的bug网上也有很多帖子说），没事就这样吧，不折腾了，能内网穿透访问看就行啦
