### ISSUE TITLE
无法检索到消息

### ISSUE THREAD

**Issue by yhzcake** [mnixry/nonebot-plugin-gocqhttp#442]
在经过一段时间后,机器人无法读取群聊中的消息,需要bot这个账号在群中发送一条消息后恢复
重启bot也会出现这个问题,但也跟时间有关,如果一段时间没有读取消息的话重启bot后也需要发送一条消息才能读取消息

**Comment by mnixry** [comment]
没有理解你的问题，能解释的再清楚一些吗👀

**Comment by yhzcake** [comment]
我现在没办法给你截图,因为这个问题可能是随机产生的,就是在一段时间某个群没有任何消息后,bot就没办法再接受这个群里的任何消息,必须这个qq号在群里发一条消息之后才能重新接受这个群的消息
我也不知道在某个群发消息后另一个群是不是也会让这个bug暂时消失,因为这个账号上只有一个群活跃

**Comment by mnixry** [comment]
> 就是在一段时间某个群没有任何消息后,bot就没办法再接受这个群里的任何消息,必须这个qq号在群里发一条消息之后才能重新接受这个群的消息

看起来这个问题似乎不属于这个插件，我认为可能你需要进行进一步的分析以定位问题
我认为问题可能属于Bot开发者（或者插件开发者），也有可能是GoCQ的Bug，或者是腾讯风控（虽然我没听说过这种品种的风控）

**Comment by yhzcake** [comment]
因为我只添加这个插件的时候就有这个bug,但是我找别人帮我手动连接gocq的时候貌似并没有这个bug,因此我认为是这个插件的问题

**Comment by yhzcake** [comment]
![image](https://user-images.githubusercontent.com/80627671/210809545-0593f498-6501-413e-a725-8109abd8fa83.png)
这里就是,在后台看不到收到消息,但机器人这个账号发一条消息后就会恢复

**Comment by mnixry** [comment]
看起来这个问题属于被腾讯风控了，因为如果是插件问题，起码GoCQ是能够收到日志并且展示的
可以试试登录更长时间或者换个协议登录来缓解风控

**Comment by yhzcake** [comment]
一般来讲应该用ipad的,但是这个号上面还挂了另一个bot占用了,所以用的安卓手表,但是也是尝试手动挂过gocq的,理论来讲账号应该没问题.不过这个小问题倒是不太影响使用

刚刚换了个macos,看看还会不会有问题

ps:info等级的log有点影响日常使用,如果我想在网络诊断完成未发现问题后面加个success的log在哪里加?

**Comment by mnixry** [comment]
> info等级的log有点影响日常使用,如果我想在网络诊断完成未发现问题后面加个success的log在哪里加?

有点难，因为这些日志不是NoneBot控制的而是直接从GoCQ转发过来的

**Comment by yhzcake** [comment]
哦原来是这样,怪不得找不到在哪里

**Comment by mnixry** [comment]
> 我看到你找了一下アトリは、高性能ですから! 这个也是gocq反回来的吗,或者在这里加一个success的log可以吗

https://github.com/mnixry/nonebot-plugin-gocqhttp/blob/e282156d25d3848c447931f8b0d244d6387ad67b/nonebot_plugin_gocqhttp/process/process.py#L125-L129

其实是有这么一个日志的，你改成SUCCESS可能需要自定义一下日志等级和名称啥的，有点麻烦

**Comment by yhzcake** [comment]
我看到了,nonebot是有success等级的log的,但是python库里的log没有,我搞不懂(

**Comment by mnixry** [comment]
> 我看到了,nonebot是有success等级的log的,但是python库里的log没有,我搞不懂(

https://github.com/nonebot/nonebot2/blob/c38437a22f8914fb19590ef75abb731acb845465/nonebot/plugin/manager.py#L151-L153

好像直接有`success`方法欸…… 你改改试试，~~改好了给个PR~~

**Comment by yhzcake** [comment]
是有,但是我不会搞(
不是开发者是这样的(
先这样用着吧
