### ISSUE TITLE
Unsupported platform: {platform.uname()!r}") from None

### ISSUE THREAD

**Issue by wudj** [mnixry/nonebot-plugin-gocqhttp#458]
RuntimeError: Unsupported platform: uname_result(system='Darwin', node='MacBook-Pro.local', release='21.6.0', version='Darwin Kernel Version 21.6.0/RELEASE_ARM64_T6000', machine='arm64')

**Comment by mnixry** [comment]
理论上M1 CPU的电脑是能正常识别处理器并且下载的 不知道为什么你这边识别出了问题

```python
from cpuinfo import get_cpu_info
print(get_cpu_info())
```

看看这个结果是多少
