### ISSUE TITLE
使用PM2作为守护进程时无法正常工作

### ISSUE THREAD

**Issue by MomentQYC** [mnixry/nonebot-plugin-gocqhttp#459]
在直接nb start时正常运行，而使用pm2时则会显示
[WARNING] nonebot_plugin_gocqhttp | [QQ] 连接到反向WebSocket Universal服务器 ws://127.0.0.1:(port)/onebot/v11/ws 时出现错误:
dial tcp 127.0.0.1:(port): connect: connection refused
查询发现该端口没有进程占用（正常应该有一个python）
之前运行很正常，安装插件重启后便异常（新增插件需要安装的依赖已安装）
plugins = ["nonebot_plugin_gocqhttp", "nonebot_plugin_petpet", "nonebot-plugin-ncm", "nonebot_plugin_code", "nonebot_plugin_remake", "nonebot_plugin_shindan"]

**Comment by mnixry** [comment]
PM2监控Python进程的时候使用子进程确实有很多玄学问题, 你看看PM2的issue里面有没有什么解决方案

**Comment by MomentQYC** [comment]
> PM2监控Python进程的时候使用子进程确实有很多玄学问题, 你看看PM2的issue里面有没有什么解决方案

排查后果断投入systemd的怀抱（）
