### ISSUE TITLE
WebUI 的登录凭证无法设置

### ISSUE THREAD

**Issue by Nthing734** [mnixry/nonebot-plugin-gocqhttp#482]
无法设置WebUI 的登录凭证

**Comment by mnixry** [comment]
缺乏必要信息

**Comment by Nthing734** [comment]
![IMG_20230206_185531](https://user-images.githubusercontent.com/109641391/216954122-e9cf1310-446d-4ac4-8945-e8614530f57c.jpg)
.env.dev配置如上

**Comment by mnixry** [comment]
`.env`文件的格式是`KEY=VALUE`, `=`附近没有空格, 不可以用`:`代替`=`

更多语法可以看: https://hexdocs.pm/dotenvy/dotenv-file-format.html
