### ISSUE TITLE
把登录信息上传到服务器之后显示token failed，本地运行正常，但是服务器还是要扫码

### ISSUE THREAD

**Issue by xi-yue-233** [mnixry/nonebot-plugin-gocqhttp#486]
![image](https://user-images.githubusercontent.com/58218656/217838362-4baa1658-4449-4575-a061-8d602877227a.png)

**Comment by mnixry** [comment]
看起来问题和本插件无关

**Comment by xi-yue-233** [comment]
> 看起来问题和本插件无关

但是这确确实实发生了，我也不知道为什么，之前一直都可以的
![image](https://user-images.githubusercontent.com/58218656/217842269-8a88538c-1cfb-43ce-bfe6-0e0aed606048.png)
本地可以运行的gocq，上服务器就要我扫码

**Comment by xi-yue-233** [comment]
解决了，是我自己nb2那边的配置问题，本地新建的nb2端口和服务器的端口不一样，登录之后上传到服务器就要重新扫码了
