### ISSUE TITLE
在WebUI中添加上传session.token登录的功能

### ISSUE THREAD

**Issue by APeng215** [mnixry/nonebot-plugin-gocqhttp#488]
我既无法通过账号密码登录，也无法通过扫码登陆。
所以请问此插件有没有提供通过session.token登录的功能？

**Comment by MistEO** [comment]
自己把 token 和 session 复制进去就好了，accounts 文件夹下

**Comment by APeng215** [comment]
> 自己把 token 和 session 复制进去就好了，accounts 文件夹下

明白了

**Comment by mnixry** [comment]
~~其实这个功能我是打算做的~~

**Comment by GrayArashiAI** [comment]
请问windows端的session token存放在哪里了。。。accounts文件夹下面什么都没有

**Comment by mnixry** [comment]
Duplicate of #559
