### ISSUE TITLE
[Security] Access Token无法设置

### ISSUE THREAD

**Issue by MomentQYC** [mnixry/nonebot-plugin-gocqhttp#496]
在`accounts/{QQ}/config.yml`中设置的`access-token`重启自动变为空值且不起效

**Comment by mnixry** [comment]
请你直接配置 `ONEBOT_ACCESS_TOKEN` 环境变量，参考文档：https://onebot.adapters.nonebot.dev/docs/guide/configuration#access_token

此外，`config.yml`是自动生成的，在任何时候都不推荐修改（修改了也没有用），请在WebUI中修改或者修改`config-template.yml`

**Comment by MomentQYC** [comment]
> 这个行为是预期的。
> 
> 请你直接配置 `ONEBOT_ACCESS_TOKEN` 环境变量，参考文档：https://onebot.adapters.nonebot.dev/docs/guide/configuration#access_token
> 
> 此外，`config.yml`是自动生成的，在任何时候都不推荐修改（修改了也没有用），请在WebUI中修改或者修改`config-template.yml`

似乎并没有生效，我在`config-template.yml`，`.env`和service文件中`Environment`项都写入了一样的值，但是重启后似乎仍然可以直接访问

**Comment by mnixry** [comment]
你所说的直接访问指的是？

**Comment by MomentQYC** [comment]
> 你所说的直接访问指的是？

可以直接打开页面，看到配置，日志等等

**Comment by mnixry** [comment]
> 可以直接打开页面，看到配置，日志等等 还可以修改配置，对机器人开关进行操作

这个是另外的配置项目，请参考README：

> `GOCQ_WEBUI_USERNAME`/`GOCQ_WEBUI_PASSWORD`: WebUI 的登录凭证, 不设置即不进行验证

**Comment by MomentQYC** [comment]
已解决，感谢
