### ISSUE TITLE
扫码一直显示失败，换号也不行，这是账号封控了吗

### ISSUE THREAD

**Issue by LeonX86** [mnixry/nonebot-plugin-gocqhttp#497]
应该是前天突然账号掉线了，然后扫描一直就是这种页面，今天有试了下插件更新到0.6.6也没用，换设备协议也没用
![Screenshot_20230217_152958_QQ](https://user-images.githubusercontent.com/49100008/219579681-901f287e-8bb5-44e0-990e-0c7b930035ea.jpg)

**Comment by mnixry** [comment]
异地扫码是这样的, 请想办法本地扫码

**Comment by LeonX86** [comment]
> 异地扫码是这样的, 请想办法本地扫码

好滴，我来试一下
