### ISSUE TITLE
进程运行中切换网络或断网需要重新认证

### ISSUE THREAD

**Issue by KotoriKoi** [mnixry/nonebot-plugin-gocqhttp#498]
使用二维码扫描登录
配置密码登录在webui上未检测输入端默认是1拉验证条显示密码错误或冻结，传入文字到进程也没有用，根本不给传入的机会就直接跳到1了，我看了下gocqhttp那边拉条验证也一堆密码错误或冻结的，不知道能不能改成默认2扫码验证。
进程运行中切换网络会导致账号密码未配置需要重新扫码登录，即使重新启动nonebot也需要重新扫码，隔壁koishi的gocqhttp则没有出现过这种情况，不知道什么原因

**Comment by NovNoah** [comment]
我也有这个问题

**Comment by yhzcake** [comment]
可以先密码留空添加账号,扫描二维码成功登录后删除这个账号,但是不要勾选删除配置文件,再输入密码重新添加账户就可以了
