### ISSUE TITLE
无法直接更换/修改 protocol (设备类型)

### ISSUE THREAD

**Issue by Well2333** [mnixry/nonebot-plugin-gocqhttp#515]
目前由于众所周知的原因，大量的设备协议无法登录，需要更换登录的设备类型，其中较为常见的方法是修改 device.json 中的 protocol 参数。

但由于 [此处](https://github.com/mnixry/nonebot-plugin-gocqhttp/blob/main/nonebot_plugin_gocqhttp/process/config.py#L94) 运行前检查强制将 protocol 替换为一开始用户所选的类型，导致 bot 启动时 protocol 参数会被记录值直接覆盖，导致无法直接更换协议。

目前可用的 **临时解决方案** 是 “在webui中保留数据的情况下删除该账号并重新添加” 以重新选择登陆设备协议。但较为麻烦，因此是否考虑移除这一校验或添加更换设备的功能？

**Comment by wei-z-git** [comment]
可以直接在配置里写死协议吗，比如
``` 
GOCQ_ACCOUNTS=[{ "uin": "xxx","protocol":2}] 
```
（这样可能账号信息需要清空重登）
