### ISSUE TITLE
暂时更换go-cqhttp下载源来解决无法登录的问题

### ISSUE THREAD

**Issue by zmy15** [mnixry/nonebot-plugin-gocqhttp#522]
![image](https://user-images.githubusercontent.com/109537161/223138487-ca0266e0-b196-4680-b29f-578f19df134e.png)
https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419

**Comment by mnixry** [comment]
迟早会发版的，别急
着急用自己把accounts/binary里面的gocq文件替换掉

**Comment by zmy15** [comment]
> 自己chmod +x给个可执行权限

直接上传的,忘改属性了(尴尬
