### ISSUE TITLE
登录协议是否可以增加aPad

### ISSUE THREAD

**Issue by LiShenshun** [mnixry/nonebot-plugin-gocqhttp#524]
https://docs.go-cqhttp.org/guide/config.html#%E8%AE%BE%E5%A4%87%E4%BF%A1%E6%81%AF

尝试把protocol改为6，控制台无法启动，后台报错不支持该协议，独立的go-cqhttp启动没这个问题。

**Comment by mnixry** [comment]
请升级你的本插件到最新版本 https://github.com/mnixry/nonebot-plugin-gocqhttp/releases/tag/v0.6.8 ，~~昨天晚上刚发~~
