### ISSUE TITLE
自定义默认模板配置无效

### ISSUE THREAD

**Issue by jyg94** [mnixry/nonebot-plugin-gocqhttp#533]
我在.env里面设置了GOCQ_CONFIG_TEMPLATE_PATH路径，并且每次删除了整个account文件夹，但是并没有替换掉config.yml。
我在源码里面调试了很久，最后发现解决方法是不要删除整个account文件夹，要保留account文件夹里面的binary，只删除用户文件。
原因貌似是__init__.py里面的这两行
    if config.FORCE_DOWNLOAD or not BINARY_PATH.is_file():
        await download_gocq()
每次发现没有binary文件都会重新下载，然后就会出现一个用户文件，使得后面的进程里监测到模板已经存在，不会导入我的GOCQ_CONFIG_TEMPLATE_PATH。
可能不算bug（当然修了更好），但还是来提醒一下，要用GOCQ_CONFIG_TEMPLATE_PATH的话只能删account里面除binary以外的文件夹。

**Comment by MistEO** [comment]
> 每次发现没有binary文件都会重新下载，然后就会出现一个用户文件，使得后面的进程里监测到模板已经存在，不会导入我的GOCQ_CONFIG_TEMPLATE_PATH。

没理解，啥意思x

**Comment by jyg94** [comment]
> 

我理解的代码逻辑是，如果acount/binary不存在，那么就会下载acount/binary，并且同时也会带上acount/user/xxx。而后面在尝试导入GOCQ_CONFIG_TEMPLATE_PATH的模板文件之前，会先检查acount/user/config-template是否已经存在，如果存在的话就不会使用GOCQ_CONFIG_TEMPLATE_PATH下的模板文件。所以不管是删除整个acount文件夹，或者是什么都不删，都不会导入GOCQ_CONFIG_TEMPLATE_PATH下的模板文件。

**Comment by MistEO** [comment]
那这个不是自定义模板的问题，你即使使用自定义模板，而是使用默认模板。在手动修改默认模板后（默认模板是跟着这个插件一起安装的，在 `<YourPathDir>/Lib/site-packages/nonebot_plugin_gocqhttp/process` 里），accounts/<uid>/ 文件夹中的也不会更新

**Comment by MistEO** [comment]
我的理解这个是设计如此，可以为不同的账号区分不同的模板文件，不然把 config-template.yml 复制一份到每个账号的目录下就没有意义了，还不如直接从总的模板生成每个账号的 config.yml

可以理解为这个自定义模板/默认模板，是每个账号的模板的模板
