### ISSUE TITLE
Linux服务器如何进行账号登陆

### ISSUE THREAD

**Issue by MeteoricShower** [mnixry/nonebot-plugin-gocqhttp#548]
无论是否设置密码，启动nonebot后均提示使用webui；如果一定要使用webui，是通过公网ip访问8080端口吗？
![image](https://user-images.githubusercontent.com/87252034/227431213-bb8e7e19-702d-4c69-bfda-8123904049b0.png)

**Comment by mnixry** [comment]
Duplicate of #42
