### ISSUE TITLE
安装后无限登录

### ISSUE THREAD

**Issue by Esmge** [mnixry/nonebot-plugin-gocqhttp#556]
昨天安装时发现一些问题
1.修改配置报错
2.修改配置似乎不会生效
3.登录两步验证下。输入1自动获取扫码后，正要输入2手机扫码验证，直接重启，根本不给机会，逼得我只得去直接使用gocq

**Comment by mnixry** [comment]
> 1.修改配置报错 

请给出具体报错信息以便调试。

> 2.修改配置似乎不会生效 

请不要直接修改`config.yml`文件，这个文件会在每次启动时被覆写。请在WebUI中修改或者修改`config-template.yml`。

> 3.登录两步验证下。输入1自动获取扫码后，正要输入2手机扫码验证，直接重启，根本不给机会，逼得我只得去直接使用gocq

能不能提供一下这个问题的详细日志，以及运行平台信息，目前没有收到这样的反馈。

**Comment by Esmge** [comment]
1.修改配置>设备信息
![image](https://user-images.githubusercontent.com/41093896/228438217-0dc9731f-b4d1-4cf8-a96d-22b8ed384c4a.png)
![image](https://user-images.githubusercontent.com/41093896/228438307-720142fc-710f-46e2-bc64-eb5795d48fb9.png)
2.我又去试了下，好像是我自己的问题。
3.到设备锁这一步，正要输入2扫码验证，直接就到滑动了
![image](https://user-images.githubusercontent.com/41093896/228437702-b7f6ad99-0610-4cd0-a1f4-8ad4cd824274.png)

以上：我不确定是不是我操作不对还是环境配置有什么问题。

**Comment by mnixry** [comment]
> 1.修改配置 > 设备信息

这个报错栈没有截取全, 请尽量提供完整日志.

> 3.到设备锁这一步，正要输入2扫码验证，直接就到滑动了

看起来问题和 #498 一样, 都是 go-cqhttp 新添加的TTY检测的问题. 我会在稍后进行修复.

**Comment by mnixry** [comment]
> 3.到设备锁这一步，正要输入2扫码验证，直接就到滑动了

你是否可以尝试设置一下环境变量

```bash
export FORCE_TTY=1
```

看看这个问题是否得到解决. (输入字符串需要通过WebUI, 控制台是不接受`stdin`的)
