### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by xi-yue-233** [mnixry/nonebot-plugin-gocqhttp#557]
![image](https://user-images.githubusercontent.com/58218656/228794975-871168cf-2f5d-4c7f-817c-955065fbffe3.png)

**Comment by MistEO** [comment]
看看你设置的文件

**Comment by xi-yue-233** [comment]
> 看看你设置的文件

![image](https://user-images.githubusercontent.com/58218656/228815485-f81ddf1d-1fc0-4313-b29a-a062953a90c5.png)
主要是在servers多设置了一个端口

**Comment by mnixry** [comment]
看看日志。这种出错一般都是有日志里面的报错的

**Comment by xi-yue-233** [comment]
> 看看日志。这种出错一般都是有日志里面的报错的

日志就是什么都没有，还没登录上，这个是登录新账号的时候报的

**Comment by xi-yue-233** [comment]
![image](https://user-images.githubusercontent.com/58218656/228821108-d4d10502-58e7-4a76-b9f3-6b81243c7c5c.png)
目前通过webui直接修改然后重启是可以使用的
