### ISSUE TITLE
[有关反代问题]当使用nginx反代127.0.0.1到0.0.0.0时

### ISSUE THREAD

**Issue by yhzcake** [mnixry/nonebot-plugin-gocqhttp#558]
如题,此时网站无法识别到正在运行的go-cqhttp客户端,并且显示 状态:断开 , log只有在点击状态按钮手动刷新才能出现,左侧栏位一直显示正在刷新,网页上方的进度条也在一直跳动,请问是否有办法正常使用?

另:最新的go-cqhttp非常好用,不过插件自动生成 的device无法使用,需要手动通过go-cqhttp.exe来生成,随后就可以享受了

**Comment by mnixry** [comment]
Duplicate of #42

**Comment by mnixry** [comment]
> 不过插件自动生成的device无法使用,需要手动通过go-cqhttp.exe来生成,随后就可以享受了

无法使用具体是什么症状能描述一下吗👀？

**Comment by yhzcake** [comment]
> > 不过插件自动生成的device无法使用,需要手动通过go-cqhttp.exe来生成,随后就可以享受了
> 
> 无法使用具体是什么症状能描述一下吗👀？

显示qq版本过旧。
我的插件版本我也不记得了，因为没写插件信息，不过添加账号的界面有apad协议了

**Comment by yhzcake** [comment]
> Duplicate of #42

我都忘了我在这里回复过了，结果又问了一遍
github用的还不是很熟练 抱歉
