### ISSUE TITLE
QDVC 协议支持

### ISSUE THREAD

**Issue by mnixry** [mnixry/nonebot-plugin-gocqhttp#559]
_QDVC是一个生成和管理 QQ Device/Session 的工具，允许你在多种环境下管理来自不同平台的虚拟设备和登录信息，仓库地址：https://github.com/ilharp/qdvc_

目前，在不同设备间迁移设备数据需要用户自行拷贝，这不仅增加了用户使用的复杂度，同时还带来了一些不可预料的问题，如上传文件的权限问题
此外，本插件目前存在随机设备Device信息的行为，但是防止风控效果并不明显（甚至有用户认为这是反作用），在引入QDVC的同时，我将从代码中移除该功能

ref: #488 

/cc @MistEO ~~你怎么想的~~

**Comment by MistEO** [comment]
刚看到 at，这个咋用呀现在（
