### ISSUE TITLE
后台运行正常但是webUI无日志记录

### ISSUE THREAD

**Issue by Arturia169** [mnixry/nonebot-plugin-gocqhttp#568]
![image](https://user-images.githubusercontent.com/69199123/229501921-9e3ee392-bb09-4573-a5f5-c6bd2ae73198.png)

Linux：debian11

**Comment by mnixry** [comment]
终端有日志吗👀
给Bot发送消息也没有日志显示？

**Comment by Arturia169** [comment]
> 终端有日志吗👀给Bot发送消息也没有日志显示？

![image](https://user-images.githubusercontent.com/69199123/229502672-f0040c55-3019-479d-be37-a1b3d6c5161e.png)
后台有日志 
给bot发消息只有后台能显示web端不显示

**Comment by Arturia169** [comment]
已自行排查解决，此贴终结

**Comment by mnixry** [comment]
👀所以是什么问题导致的

**Comment by Arturia169** [comment]
> 👀所以是什么问题导致的

机器上原本有个独立的gocq我将其停止后使用该插件版登录就好了
