### ISSUE TITLE
每次重新启动nonebot，webui上账号列表都为空

### ISSUE THREAD

**Issue by Feiyuyu0503** [mnixry/nonebot-plugin-gocqhttp#575]
插件版本 0.6.10
gocqhttp v1.0.1
系统环境 Linux amd64 Ubuntu 18.04
问题：
每次重新启动nonebot，qq都不会自动登录，要去webui登录，且webui没有记忆之前的登录账号，需要重新添加qq

**Comment by Feiyuyu0503** [comment]
把nonebot2从v2.0.0rc4降级到v2.0.0rc3就好了

**Comment by mnixry** [comment]
```shell
pip install fastapi -U
```

升级一下FastAPI试试

**Comment by Feiyuyu0503** [comment]
谢谢，fastapi从0.89.1升级到了0.95.0，nonebot2升级到v2.0.0rc4，可以正常登录了。
