### ISSUE TITLE
如何配置ws的地址

### ISSUE THREAD

**Issue by happy-bear-x** [mnixry/nonebot-plugin-gocqhttp#591]
直接在account下修改config.yaml后启动还是会在/go-cqhttp/ws下，如何自定义呢？

**Comment by mnixry** [comment]
没有理解你的需求

**Comment by happy-bear-x** [comment]
> 没有理解你的需求

在account下有这样的配置
servers:
  - ws-reverse:
      universal: "ws://127.0.0.1:8181/onebot/v11/ws"
      reconnect-interval: 3000
      middlewares:
        <<: *default
        access-token: ""

我改成ws://127.0.0.1:8181/ws后再下次启动后依旧是ws://127.0.0.1:8181/onebot/v11/ws

**Comment by mnixry** [comment]
那你为什么要改他呢？NoneBot2又不会接受来自其他地方的上报，改了会出问题

---

如果你确实想改，请在WebUI里修改，或者修改`config-template.yml`
