### ISSUE TITLE
如何在启动时运行 gocq的更新协议功能 -update-protocol

### ISSUE THREAD

**Issue by sajfasjg81** [mnixry/nonebot-plugin-gocqhttp#614]
似乎在网页控制台输入用不了

**Comment by sajfasjg81** [comment]
还有 有没有直接重置dev+切换协议的api

目前使用 删除+添加的API 单独做了个功能达到了切换协议效果

**Comment by mnixry** [comment]
这个功能确实没做，主要是我没有想好该怎么做交互，总不可能每次启动都带一个 `-update-protocol` 参数

~~而且我观察，协议更新与否并不影响能否登录和消息风控等情况，所以一直拖着没做~~

> 还有 有没有直接重置dev+切换协议的api

现在改协议直接走修改`device.json`的API就可以了，检测到协议字段更改会自己更新的

**Comment by mnixry** [comment]
不用close，做了就关了，不做挂在这也方便定位

**Comment by sajfasjg81** [comment]
好

**Comment by mnixry** [comment]
见：https://github.com/Mrs4s/go-cqhttp/issues/2183

目前认为，`-update-protocol`更新客户端版本后，反而会增加无法登录的概率（因为协商版本和TLV544版本不一致），所以这个功能先不做了

**Comment by mnixry** [comment]
现在默认每次启动都有 `-update-protocol` 了，算是临时方案吧。
