### ISSUE TITLE
如何更新该插件的设备协议

### ISSUE THREAD

**Issue by AQR0124** [mnixry/nonebot-plugin-gocqhttp#615]
“登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试 ”，如何更新该插件的设备协议，使用的协议: MacOS 5.8.9

**Comment by mnixry** [comment]
更新你的 `go-cqhttp` 版本至最新。如果已是最新那就是腾讯的问题

**Comment by AQR0124** [comment]
> 更新你的 `go-cqhttp` 版本至最新。如果已是最新那就是腾讯的问题

当时的插件是尝试更新过的，但依然提示需要更新协议

**Comment by mnixry** [comment]
> 同样的问题，今天发现所有协议都寄了。。。怎么都登不上去，话说-update-protocol怎么输入，直接文本输入？还是./go-cqhttp -update-protocol 好像都没法更新协议

Duplicate of #614 

这个功能还没做……今晚想办法解决一下吧

**Comment by zhoyk** [comment]
![QQ截图20230526185401](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/118122497/918099dc-1780-4d14-a840-3625c05c0277)
怎么办，一直登陆不了

**Comment by mnixry** [comment]
related: https://github.com/Mrs4s/go-cqhttp/issues/2183
