### ISSUE TITLE
在replit部署资源未成功加载，服务器显示404

### ISSUE THREAD

**Issue by superdaobo** [mnixry/nonebot-plugin-gocqhttp#630]
之前有一次不知道怎么nonebot-plugin-gocqhttp可以在replit上运行了，于是开了快半个月，后来好像因为SSL的问题，bot的web一直访问不了，于是删除重新开了一个，然后便显示如下错误，但是资源在本地都有，有大佬知道什么情况吗？

![屏幕截图 2023-06-04 191250](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/83578139/4fece49b-82d0-44b8-8a61-734e8ab16e4e)
![屏幕截图 2023-06-04 191724](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/83578139/374643ac-0b26-4930-b435-af7234dc6fa2)

**Comment by mnixry** [comment]
不懂，没用过，但是看着没什么问题.jpg

```dotenv
gocq_mute_access_log=true
```

试试`.env`里面加这一行，看看日志

**Comment by superdaobo** [comment]
> 不懂，没用过，但是看着没什么问题.jpg
> 
> ```dotenv
> gocq_mute_access_log=true
>  #```
> 
> 试试`.env`里面加这一行，看看日志
按照您说的，在.env文件添加了但是控制台的输出好像没有任何变化（
我的问题就是进入web界面时因为资源加载不完全导致无法启动。
很奇怪，明明都在同一个文件夹，有的文件可以加载，有的就404。
麻烦大佬再看一下，
![屏幕截图 2023-06-05 225642](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/83578139/7e8bd702-0e9c-4586-baf6-f876d3010b50)
![屏幕截图 2023-06-05 225714](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/83578139/f56226f3-eb71-4276-81f2-f45b580caed4)

**Comment by mnixry** [comment]
Ctrl+F5 刷新网页。如果不行就清除网站数据再刷新。

**Comment by mnixry** [comment]
![image](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/32300164/8ec53556-6967-44f5-ac50-de7b3c8c291f)

还真是。我不理解.jpg

可能是打包出问题了，但是这个版本发布好久了也妹见人反馈啊.jpg

**Comment by mnixry** [comment]
![image](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/32300164/acd182d0-bae2-4391-aa09-486f49a1eeeb)

但是这个文件明明是存在的……迷惑

**Comment by mnixry** [comment]
简单调了一下，基本可以确定这个问题是replit的Python包管理器有问题，和本仓库无关

**Comment by superdaobo** [comment]
> 简单调了一下，基本可以确定这个问题是replit的Python包管理器有问题，和本仓库无关

是指nonebot包有问题吗，我把site-packages里的直接甩到plugins里运行也是这样的问题。
大佬有什么解决方案吗_φ_(．．)

**Comment by mnixry** [comment]
就是replit有问题。他魔改了包管理器，弄了一个很神秘的包安装方式，然后这个安装方式有Bug。
理论上应该可以你把这个插件包目录的`./web/dist` 用 https://github.com/mnixry/nonebot-plugin-gocqhttp/actions/runs/5154431284 这个压缩包里面的内容覆盖掉就能用

**Comment by superdaobo** [comment]
> 就是replit有问题。他魔改了包管理器，弄了一个很神秘的包安装方式，然后这个安装方式有Bug。我也不是第一次遇到replit他们的神秘Bug了，[mixmoe/HibiAPI#253](https://github.com/mixmoe/HibiAPI/issues/253) 问题差不多，就是他们瞎搞非要把自己的SDK整合进去。 理论上应该可以你把这个插件包目录的`./web/dist` 用 https://github.com/mnixry/nonebot-plugin-gocqhttp/actions/runs/5154431284 这个压缩包里面的内容覆盖掉就能用

可以了可以了，我把nonebot和nb-cli和nonebot-plugin-gocqhttp重装了一遍就可以打开了（喜）
![屏幕截图 2023-06-06 123024](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/83578139/19964a95-e7f1-41ba-a800-9c16c94b26e0)
