### ISSUE TITLE
怎么设置-update-protocol参数

### ISSUE THREAD

**Issue by SerPolar** [mnixry/nonebot-plugin-gocqhttp#647]
06-23 17:43:02 [WARNING] nonebot_plugin_gocqhttp | [3429955397] 登录失败: 当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。 Code: 237
06-23 17:43:02 [WARNING] nonebot_plugin_gocqhttp | [3429955397] 登录过于频繁, 请在手机QQ登录并根据提示完成认证后等一段时间重试
06-23 17:43:02 [INFO] nonebot_plugin_gocqhttp | [3429955397] 按 Enter 继续....

**Comment by mnixry** [comment]
Duplicate of #614
