### ISSUE TITLE
go-cqhttp 增加了一个 Account.SignServer 字段用来配置签名服务器，有考虑加上吗？

### ISSUE THREAD

**Issue by TheLZY** [mnixry/nonebot-plugin-gocqhttp#653]
https://github.com/Mrs4s/go-cqhttp/issues/2242

还是直接改template比较方便？

**Comment by mnixry** [comment]
这个字段能留空吗（
能留空的话你PR一个把这个加到默认Template里面吧，留空加一行注释

**Comment by TheLZY** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/9c1390c75c97bbed5b153abffaa45b2ed3a1c360/cmd/gocq/main.go#L167C2-L173C3
看起来是可以留空的

不过鉴于大概率很多人会蹭别人搭的服务，会经常改，似乎留一个配置比较好（
晚上我有电脑了研究研究再扔叭（

**Comment by TheLZY** [comment]
试了一下，并不能留空，默认是 `sign-server: '-'` 
其他版本的go-cqhttp倒是不会读这个字段，加进去似乎不会影响运行
姑且先提一个pr罢（

不过按照评论 https://github.com/Mrs4s/go-cqhttp/discussions/2245#discussioncomment-6300987  ，用了自建的签名服务器后冻结的概率仍然很高，有没有效果还是可以再观望一下（

**Comment by mnixry** [comment]
我过会可能还需要改一下生成`device.json`的逻辑，现在生成的Android ID是每个账号不一样的，会比较麻烦

**Comment by moemeow233** [comment]
大佬，试了一下在config.yaml里添加`sign-server 'http://127.0.0.1:8080'`之后启动bot，但是还是输出未使用签名服务器，请问如何解决？[1](https://img1.imgtp.com/2023/07/01/kmATLEYo.PNG)[2](https://img1.imgtp.com/2023/07/01/HQXLDFqH.PNG)

**Comment by TheLZY** [comment]
> 大佬，试了一下在config.yml里添加`sign-server: 'http://127.0.0.1:8080'`之后启动bot，但是还是输出未使用签名服务器，请问如何解决？ [log](https://img1.imgtp.com/2023/07/01/kmATLEYo.PNG) [config](https://img1.imgtp.com/2023/07/01/HQXLDFqH.PNG)



https://github.com/mnixry/nonebot-plugin-gocqhttp/blob/227ef890cce5d31b74def2c5fe679851c86a76b2/nonebot_plugin_gocqhttp/process/process.py#L202-L204

https://github.com/mnixry/nonebot-plugin-gocqhttp/blob/227ef890cce5d31b74def2c5fe679851c86a76b2/nonebot_plugin_gocqhttp/process/config.py#L47-L62

每次开启应该都会根据template重新生成
所以可以试试直接改template（
