### ISSUE TITLE
请问如何更新cq版本到最新版啊，更新了这个插件可是cq还是旧版本

### ISSUE THREAD

**Issue by Tiannuo** [mnixry/nonebot-plugin-gocqhttp#657]

**Comment by mnixry** [comment]
删掉 `accounts/binary` 里面的可执行文件，就会自动下载最新。

**Comment by Tiannuo** [comment]
> 删掉 `accounts/binary` 里面的可执行文件，就会自动下载最新。
config-template.yml 这个文件里面没有签名字段？
