### ISSUE TITLE
如何添加正向ws接口？

### ISSUE THREAD

**Issue by YipSzeho** [mnixry/nonebot-plugin-gocqhttp#68]
在config里修改了，但重启bot后配置的信息就会重置，只剩下了反向ws。另一个bot需要使用正向ws，请问该怎么设置呢？

**Comment by mnixry** [comment]
> 在config里修改了，但重启bot后配置的信息就会重置，只剩下了反向ws。

每次启动的时候都会生成新的配置文件覆盖, 预期行为确实是这样(其实一种比较偷懒的写法)

> 另一个bot需要使用正向ws，请问该怎么设置呢？

请参考[README的进行配置一项](https://github.com/mnixry/nonebot-plugin-gocqhttp#%E8%B4%A6%E5%8F%B7%E9%85%8D%E7%BD%AE), 可以使用`ref:`或者`override:`直接引入一个外部的配置文件

这似乎不是一个很优雅的做法, 但是我也没想到什么比较好的代替方案

**Comment by mnixry** [comment]
在 https://github.com/mnixry/nonebot-plugin-gocqhttp/tree/v0.5.0 中, 我尝试重构了配置文件的生成设置

现在, 你可以在WebUI中直接编辑配置文件, 或者编辑账户文件夹中的`config-template.yml`

---

因为这个功能的推出, 我个人认为配置文件修改应该变得相当便利了, 所以我将会关闭该Issue.

如果你有任何进一步的问题, 欢迎随时Reopen或者提交一个新的Issue.
