### ISSUE TITLE
TypeError: __call()__ missing 1 required positional argument: ‘request’

### ISSUE THREAD

**Issue by aoguai** [mnixry/nonebot-plugin-gocqhttp#684]
用 nb plugin install nonebot-plugin-gocqhttp 指令安装插件，同时在项目下 .env.prod 设置了GOCQ_WEBUI_USERNAME/GOCQ_WEBUI_PASSWORD后会出现报错：
![IEN{ CVR3S5FP PNNT({D](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/34203474/ed84f244-974e-468c-8520-0aec9f6fab16)
配置如下：
![IQMP3`V26T22C)UMTDU0{(8](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/34203474/c677f4ba-5ab8-4ef9-af5b-496d3b19dea0)
删掉 GOCQ_WEBUI_USERNAME/GOCQ_WEBUI_PASSWORD 后恢复正常。
已知原始环境是用 nb-cli 引导构建，fastapi 0.101.1。

暂时解决办法：发现 #656 存在类似情况。
尝试对 fastapi 进行降级，降级到 0.96.0 报错消失。

**Comment by mnixry** [comment]
同样无法复现。如果可能能否提供完整的错误堆栈？

**Comment by aoguai** [comment]
> 同样无法复现。如果可能能否提供完整的错误堆栈？

错误堆栈没有保存（悲
好不容易才找到的一张当时的截图（因为当时在群里问了所有截的图），能找到的话我就直接提供了😢...

**Comment by mnixry** [comment]
没事，我这边复现出来了

可能这个真的是FastAPI的Bug（也有可能给WebSocket设置HTTPBasic验证属于未定义行为，实践上应该避免），我会向上游报告，感谢提供线索。

**Comment by aoguai** [comment]
好的👌🏻😉

**Comment by mnixry** [comment]
你确定你降级到的是 0.96.0 吗？我在 0.96.0 仍然能够复现该问题。

**Comment by mnixry** [comment]
related: https://github.com/tiangolo/fastapi/discussions/8983

看起来这个问题从2021年开始就已经存在了。不知道为什么降低FastAPI版本会有效果。

**Comment by aoguai** [comment]
> related: [tiangolo/fastapi#8983](https://github.com/tiangolo/fastapi/discussions/8983)
> 
> 看起来这个问题**最晚**从2021年开始就已经存在了。不知道为什么降低FastAPI版本会有效果。

看了一下，根据讨论内容，问题的核心在于 OAuth2PasswordBearer 这个依赖是设计用来在 HTTP 请求中获取并验证 JWT token 的，但是在 WebSocket 请求中，并没有 request 这个对象的概念，因此无法直接使用这个依赖。WebSocket 请求和 HTTP 请求的处理方式是不同的，而 FastAPI 的安全依赖目前只针对 HTTP 请求进行了设计和实现。有人建议在 WebSocket 的处理函数中，直接使用 websocket.headers 来获取 X-Authorization 头部信息，而不是使用 OAuth2PasswordBearer，或者可以为 WebSocket 请求创建一个类似于 OAuth2PasswordBearer 的自定义解决方案，用来处理验证逻辑。这可能需要一些额外的工作，但是可以满足 WebSocket 的需求。

等待更多的官方支持： 一些讨论者表示他们在 FastAPI 或 Starlette 的代码库中找到了与此相关的 Pull Request，这可能意味着未来的版本可能会添加对 WebSocket 安全的更好支持。

总的来说，问题的根本是 OAuth2PasswordBearer 这个安全依赖在设计时没有考虑到 WebSocket 请求的场景，因此当前的实现无法直接适用于 WebSocket。解决这个问题可能需要使用上述提到的方法之一，或者等待 FastAPI 更新，以便在未来的版本中获得更好的 WebSocket 安全支持。
（GPT总结的）

**Comment by mnixry** [comment]
related: https://github.com/tiangolo/fastapi/pull/10147
