### ISSUE TITLE
无论如何配置都提示未配置签名

### ISSUE THREAD

**Issue by purelolly** [mnixry/nonebot-plugin-gocqhttp#692]
09-04 02:47:09 [WARNING] nonebot_plugin_gocqhttp | Process for 1985689 exited with code -15, retrying to restart... (0/-1)
09-04 02:47:26 [STDOUT] nonebot_plugin_gocqhttp | [1985689] [2023-09-04 02:47:26] [INFO]: 当前版本:f16d72f
09-04 02:47:26 [INFO] nonebot_plugin_gocqhttp | [1985689] 将使用 device.json 内的设备信息运行Bot.
09-04 02:47:26 [WARNING] nonebot_plugin_gocqhttp | [1985689] no sign server configured
09-04 02:47:26 [WARNING] nonebot_plugin_gocqhttp | [1985689] 警告: 未配置签名服务器或签名服务器不可用, 这可能会导致登录 45 错误码或发送消息被风控
09-04 02:47:26 [INFO] nonebot_plugin_gocqhttp | [1985689] 开始尝试登录并同步消息...
09-04 02:47:26 [INFO] nonebot_plugin_gocqhttp | [1985689] 使用协议: iPad 8.9.33.614
09-04 02:47:26 [INFO] nonebot_plugin_gocqhttp | [1985689] Protocol -> connect to server: 120.232.130.13:8080
09-04 02:47:26 [WARNING] nonebot_plugin_gocqhttp | [1985689] 登录需要滑条验证码, 请验证后重试.
09-04 02:47:26 [WARNING] nonebot_plugin_gocqhttp | [1985689] 请选择提交滑块ticket方式:
09-04 02:47:26 [WARNING] nonebot_plugin_gocqhttp | [1985689] 1. 自动提交
09-04 02:47:26 [WARNING] nonebot_plugin_gocqhttp | [1985689] 2. 手动抓取提交
09-04 02:47:26 [WARNING] nonebot_plugin_gocqhttp | [1985689] 请输入(1 - 2)：

![}0O554 V@YVJ1{JND3`%QC6](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/78009999/cbb94dd8-8039-4718-9671-d9bea4737bc3)
![}@U`F 18 )B $S4%Q}WP](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/78009999/1cb4212c-9a9d-4661-bf64-f5c47186a7d7)
![0CM@XC((}3WT2ENGN_K8KM8](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/78009999/7ed08aa7-71fc-4d03-bb44-d5347bf9cf89)

**Comment by mnixry** [comment]
go-cqhttp dev分支上周把签名服务器字段名称改了，ref: https://github.com/Mrs4s/go-cqhttp/pull/2389

**Comment by purelolly** [comment]
> go-cqhttp dev分支上周把签名服务器字段名称改了，ref: [Mrs4s/go-cqhttp#2389](https://github.com/Mrs4s/go-cqhttp/pull/2389)

sign-servers:
    - "127.0.0.1:8080" 
    - "192.168.1.6:8801"
    
    也不行啊

**Comment by lgc2333** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/dev/modules/config/default_config.yml

**Comment by purelolly** [comment]
> https://github.com/Mrs4s/go-cqhttp/blob/dev/modules/config/default_config.yml

感谢
