### ISSUE TITLE
ValueError: Adapter 'OneBot V11' is not registered yet.

### ISSUE THREAD

**Issue by AlaricNorris** [mnixry/nonebot-plugin-gocqhttp#710]
https://zhuanlan.zhihu.com/p/622009333
跟着知乎大佬操作下来，我安装的nonebot好像是最新版的，OneBot直接内置v12了
结果安装这个插件后无法正常使用
09-23 11:29:39 [ERROR] nonebot | Failed to import "nonebot_plugin_gocqhttp"
ValueError: Adapter 'OneBot V11' is not registered yet.

**Comment by mnixry** [comment]
OneBot V12 和 V11 完全是两个东西，GoCQ只支持后者，所以你必须用v11的adapter

**Comment by AlaricNorris** [comment]
卧槽大佬秒回？那我相当于得自己降版本才行吗？这个v11 adapter可以手动安装码

**Comment by mnixry** [comment]
你装的时候让你选了啊，装V11还是V12

**Comment by AlaricNorris** [comment]
好的，我重装一下试试看，感谢大佬指点

**Comment by AlaricNorris** [comment]
有适配器商店  https://nonebot.dev/store
可以找到安装命令，以后类似的可以在这里解决，谢谢大佬
nb adapter install nonebot-adapter-onebot
