### ISSUE TITLE
能不能对gocq的dev分支做一个适配

### ISSUE THREAD

**Issue by aknyzsd** [mnixry/nonebot-plugin-gocqhttp#719]
现在登qsign需要用gocq的dev分支了，我替换了一下文件夹下的gocqhttp.exe并修改了配置文件，显示没有配置qsign服务器或者不可用，但是gocq.exe可以用qsign登录了

**Comment by mnixry** [comment]
#692

**Comment by aknyzsd** [comment]
出现了新的问题，如图，并未加载version文件，并且不能读取密码了![Screenshot_20231004_181446_com.wujie.connect.jpg](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/121467598/1e20f6cd-20f3-49ef-9d66-0abae1cb4853)![Cache_-50a7e354aaf8626a.jpg](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/121467598/4428573c-6936-471e-80a6-1ad78f71a376)![Cache_-48d533b1f4a3a4c9.jpg](https://github.com/mnixry/nonebot-plugin-gocqhttp/assets/121467598/fee094ec-9458-4bfc-ac49-6b2b5ff0ec34)

**Comment by mnixry** [comment]
你配置文件格式还是有问题。另外不要直接改config.yml，会在启动的时候被覆盖。

**Comment by aknyzsd** [comment]
> 你配置文件格式还是有问题。另外不要直接改config.yml，会在启动的时候被覆盖。

我是在网页端改的（网页每改一个字都会回到顶端），咋改都显示我没配置密码，我把我从网页端的配置复制下来放到gocq.exe就没问题
