### ISSUE TITLE
当前版本对应gocq_http的什么版本？要用什么版本的签名服务器

### ISSUE THREAD

**Issue by luluxiaoyu** [mnixry/nonebot-plugin-gocqhttp#720]
gocqhttp最新发布版本是1.1.0 但是用对应的签名服务还是无法登录
https://github.com/rhwong/unidbg-fetch-qsign-onekey/releases
这里似乎提供了dev版的gocq http 有办法使用吗

**Comment by mnixry** [comment]
替换 `accounts/binary` 目录中的二进制文件。

**Comment by luluxiaoyu** [comment]
好的 谢谢
