### ISSUE TITLE
返图哟

### ISSUE THREAD

**Issue by pthmz** [mnixry/nonebot-plugin-gocqhttp#77]
![屏幕截图 2022-03-20 191732](https://user-images.githubusercontent.com/97567575/159159758-3f8b9165-ba23-43fd-bfa7-cdc27cd9d6c3.png)
![图片](https://user-images.githubusercontent.com/97567575/159159878-6928cda1-4745-4291-97c8-e24ccca5c6ae.png)
![图片](https://user-images.githubusercontent.com/97567575/159159882-0238833a-8d16-4c8d-8d2a-74fb19cd16d6.png)

**Comment by mnixry** [comment]
感谢提供, 已在 https://github.com/mnixry/nonebot-plugin-gocqhttp/commit/c54d30b0927ab50e3c51150afb40601f9ff7194c 中加入README, 并已通过`co-author`的方式将您添加到该仓库的贡献者

**Comment by mnixry** [comment]
@all-contributors please add @pthmz  for doc
